title: <p align="center"> Shyryn Ospanova </p>
logo: "/assets/img/profile2.jpg"
description:
  <p align="center">
  <br> oshyryn@seas.upenn.edu
  <br> <a href="pdf/Shyryn_Ospanova_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shirin-ospanova/">LinkedIn</a> |
  <a href="https://github.com/re1null0">GitHub</a>
  </p>
  
  <p align="justify">
  Hey, I’m Shyryn, an applied ML Engineer finishing a Systems Science & Engineering degree at Penn. 
  <br>
  I build low-latency ML pipelines—from clinical speech-to-text and patent-search RAG systems to real-time perception and control stacks for autonomous robots. 
  <br>
  My work has shipped in hospitals, sped up 3D digital-twin reconstruction, and earned IEEE and Nature publications. I love turning research ideas into production-ready tools that stay fast, interpretable, and reliable.  <br><br>
  </p>
  
theme: jekyll-theme-minimal
